CREATE TABLE IF NOT EXISTS `ohn14_registrants` (
  `Gamertag` varchar(100) NOT NULL,
  `Pass_type` varchar(100) NOT NULL,
  `First_name` varchar(100) NULL,
  `Last_name` varchar(100) NULL,
  `Email` varchar(100) NOT NULL,
  `Contact_number` varchar(100) NULL,
  `State` varchar(100) NOT NULL,
  `SF` tinyint(1) NOT NULL,
  `TK` tinyint(1) NOT NULL,
  `MK` tinyint(1) NOT NULL,
  `A1` tinyint(1) NOT NULL,
  `A2` tinyint(1) NOT NULL,
  `S1` tinyint(1) NOT NULL,
  `S2` tinyint(1) NOT NULL,
  `S3` tinyint(1) NOT NULL,
  `S4` tinyint(1) NOT NULL,
  `DIY1`tinyint(1) NOT NULL,
  `DIY2`tinyint(1) NOT NULL,
  `DIY3`tinyint(1) NOT NULL,
  `DIY4`tinyint(1) NOT NULL,
  `DIY5`tinyint(1) NOT NULL,
  `DIY6`tinyint(1) NOT NULL,
  `DIY7`tinyint(1) NOT NULL,
  `DIY8`tinyint(1) NOT NULL,
  `DIY9`tinyint(1) NOT NULL,
  `DIY10`tinyint(1) NOT NULL,
  `DIY11`tinyint(1) NOT NULL,
  `DIY12`tinyint(1) NOT NULL,
  `Payment_ID` varchar(100) NULL,
  `Payment_status` varchar(100) NULL,
  `Payer_ID` varchar(100) NULL,
  `Payment_date` varchar(100) NULL,
  `Registration_date` varchar(100) NULL,
  `Shirt_size` varchar(100) NULL,
  `S2_Notes` varchar(300) NULL,
  `S4_Notes` varchar(300) NULL,
  `DIY10_Notes` varchar(300) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
